config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    get :auto_suggest, on: :collection
  end
  resources :employees do
    get :auto_suggest, on: :collection
  end

end

app/models/concerns/auto_suggestable .rb
#module Auto_suggestable
  #extend ActiveSupport::Concern

  #included do
   # has_many :auto_suggests, as: :auto_suggestable
  #end

app/models/employee.rb
class Employee < ActiveRecord::Base

  mount_uploader :image, ImageUploader
  has_and_belongs_to_many :projects
  # has_many :auto_suggests as: :auto_suggestable 
  validates_processing_of :image
  validate :image_size_validation
  validates :emp_name, :employee_id, :designation, presence: true
  validates_length_of :designation, :maximum => 20 
  validates_uniqueness_of :employee_id
  private

    def image_size_validation
      unless self.image.blank?
        errors.add(:image, "should be less than 2MB") if image.size > 2.megabytes
      end
    end
end 

app/models/employees_project.rb
class EmployeesProject < ActiveRecord::Base
  belongs_to :project
  belongs_to :employee
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_and_belongs_to_many :employees
  #has_many :auto_suggests as: :auto_suggestable 

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  #autocomplete :id ,:name
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :current_employee, only: [:show, :edit, :update, :destroy]
  def auto_suggest
    employees = Employee.where("emp_name RLIKE ?", params[:term])
  
    render json: employees.as_json(:only => [:id, :emp_name])
  end

  def index
   unless params[:query_text].blank?
      @employees = Employee.where("emp_name RLIKE ?", params[:query_text])  
    else
      @employees =Employee.all
    end
    
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
   
    if @employee.save
      redirect_to @employee, notice: "New employee created successfully."
    else
      render :new
    end
  end

  def update
    if @employee.update(employee_params)
      redirect_to employee_path(@employee)
    else
      render :edit
    end
  end
  

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    redirect_to employees_path
  end

  private
    def employee_params
      params.require(:employee).permit(:employee_id, :emp_name, :designation, :image, project_ids: [])
    end 

    def current_employee
      @employee = Employee.find(params[:id])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :current_project, only: [:show, :edit, :update, :destroy]

  def auto_suggest
    projects = Project.where("name RLIKE ?", params[:term])
  
    render json: projects.as_json(:only => [:id, :name])
  end

  def index
    unless params[:query_text].blank?
      @projects = Project.where("name RLIKE ?", params[:query_text])  
    else
      @projects = Project.all
    end
    
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
   
    if @project.save
      redirect_to @project, notice: "New project created successfully."
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end
  
  def destroy
    if @project.destroy
      redirect_to projects_path, notice: "Record deleted successfully."
    else
      redirect_to projects_path, alert: "Error: Record not deleted"
    end
  end

  private
    def project_params
      params.require(:project).permit(:name, :description, :tech_stack, :clent_details,
        employee_ids: [])
    end 

    def current_project
      @project = Project.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/employees/_form.html.erb
<%= simple_form_for @employee do |p| %>
  <p>
 <b><%= p.label :'Employee ID:',:class => 'spacinga'%></b>
  <%= p.text_field :employee_id ,required:true ,placeholder:"enter employee id",:class => 'form-control'%></b>
</p>
<p>
 <b>  <%= p.label :'Employee name :',:class => 'spacinga'%></b>
  <%= p.text_field :emp_name, as: :text, placeholder: "enter name",:class => 'form-control'%></b>
  </p>

  <p>
  <b><%= p.label :'Designation:',:class => 'spacinga' %></b>
  <%= p.text_field :designation,placeholder:"Enter employee designation",:class => 'form-control' %>
</p>

<p>

 <b><%= p.label :'Image :' ,:class => 'spacinga'%></b>
 <%= p.file_field :image , :class=>"avatar", :alt=>"Avatar"
%></b></p>
<p>
 <b>  <%= p.label :'Choose a project' ,:class => 'spacinga'%></b>
<%= p.association :projects, as: :check_boxes, collection: Project.order(:name) %>
 
<div class ="spacinga">
  <%= p.button :submit, :class=> "btn btn-sm btn-primary " %>
   

<% end %>

app/views/employees/edit.html.erb
<div class="spacing">
  <link rel="stylesheet" href="application.css">
  <h3 style="color:Tomato;">Update Employee Details</h3></div>
  <%= render "form" %>
</div>

app/views/employees/index.html.erb
<h2>EMPLOYEE</h2>

   <div class="container">
    
  <%= form_tag employees_path, method: :get, id: "searchForm" do %>
  <div class="input-group">  
    <%= text_field_tag :query_text, params[:query_text], 
      placeholder: "Search employees..." ,class: "form-control" %>
       <div class="input-group-btn">    
    </div>  
  </div>
  <% end %>  
</div>

<br>
<p class="float-right">
  <%= link_to "Add employee", new_employee_path, class: "btn btn-md btn-primary" %>
</p>

<% unless @employees.blank? %>
  <table class="table table-hover table-bordered table-striped ">
    <thead>
      <tr>
        <th>Sl No.</th>
        <th>Name</th>
        
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each_with_index do |employee, index| %>
        <tr>
          <td><%= index + 1 %></td>  
          <td><%= employee.emp_name %></td>
          
          <td>
            <div>
              <%= link_to "Show", employee_path(employee), 
                class: "btn btn-sm btn-success" %>
              <%= link_to "Edit", edit_employee_path(employee), 
                class: "btn btn-sm btn-primary" %>
              <%= link_to "Remove",employee_path(employee), method: 'delete',
                class: "btn btn-sm btn-danger", data: { confirm: 'Are you sure?' } %>
            </div>
          </td>
        </tr>
      <% end %> 
    </tbody>
  </table>
<% else %>
  <center><h3>No project found to be shown here!</h3></center>
<% end %>


<link href=" http://code.jquery.com/ui/1.9.1/themes/pepper-grinder/jquery-ui.css" rel="Stylesheet"></link>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
   
<script type="text/javascript">
  $("#query_text").autocomplete({
    minLength: 1,
    source: "<%= auto_suggest_employees_path %>",
    select: function(event, ui) {
      $("#query_text").val(ui.item.emp_name);
      $("#searchForm").submit();
      return false;
    }
  }).data("ui-autocomplete")._renderItem = function(ul,item) {
    return $("<li class='list-group-item list-group-item-primary'></li>")
    .data("item.autocomplete", item)
    .append("<a>"+item.emp_name+"</a>")
    .appendTo(ul);
  }
</script>

app/views/employees/new.html.erb
<div class="spacing">
  <link rel="stylesheet" href="application.scss">

  <h1 style="color:Tomato;">Create Employee</h1>
  <%= render "form" %>

</div>

app/views/employees/show.html.erb
<center><h3> Employee Details </h3> </center>
<hr>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @employee.image, height: "164px", width: "180px",
        class: "rounded mx-auto d-block" %>  
    </div>
    <div class="col-md-8">
      <table class="table table-striped">
      <tr>
        <th>Emplyee ID</th>
        <td><%= @employee.employee_id %></td>
      </tr> 
      <tr>
        <th>Name</th>
        <td><%= @employee.emp_name %></td>
      </tr>
      <tr>
        <th>Designation</th>
        <td><%= @employee.designation %></td>
      </tr>
      <tr>
        <th>Assigned Project(s)</th>
        <td>
          <ul class="list-group">
            <% @employee.projects.each do |proj| %>
              <li class="list-group-item list-group-item-info">
                <%= proj.name %>
              </li>
            <% end %>
          </ul>
        </td>
      </tr> 
      </table> 
    </div>
  </div> 
</div>

<%= link_to 'Back', employees_path,class: "ml-2 btn btn-sm btn-primary" %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubyapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if notice %>
    <div class="row alert alert-primary">
      <center><%= notice %></center>
    </div>
  <% end %>

  <% if alert %>
    <div class="row alert alert-danger">
      <center><%= alert %></center>
    </div>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for @project do |p| %>
  <p>
 <b><%= p.label :'Project name :',:class => 'spacinga',:class => 'spacinga'%></b>
  <%= p.input_field :name ,required:true ,placeholder:"Enter project name",:class => 'form-control'%></b>
</p>
<p>
 <b>  <%= p.label :'Description :',:class => 'spacinga'%></b>
  <%= p.text_field :description, as: :text, placeholder: "Add description of this project here", :input_html => {:minlength => 0 , maxlength: 1024} ,:class => 'form-control'%></b>
  </p>

  <p>
  <b><%= p.label :'Techstack :',:class => 'spacinga' %></b>
  <%= p.text_field :tech_stack,placeholder:"Enter Techstack used in  project",:class => 'form-control' %>
</p>

<p>
 <b><%= p.label :'Client details :' ,:class => 'spacinga'%></b>
 <%= p.text_field :clent_details,placeholder:"Enter client details",:class => 'form-control' %>
 </b></p>

 <b>  <%= p.label :'Choose employees to assign' ,:class => 'spacinga'%></b>
<%= p.association :employees, as: :check_boxes, collection: Employee.order(:emp_name) %>
 
  
<div class ="spacinga">
  <%= p.button :submit, class: "btn btn-sm btn-primary " %>
<% end %>

app/views/projects/edit.html.erb
<div class="spacing">
  <link rel="stylesheet" href="application.css">
  <h3 style="color:Tomato;">Update project Details</h3></div>
  <%= render "form" %>
</div>

app/views/projects/index.html.erb
 <h2>Projects</h2>

   <div class="container">
    
  <%= form_tag projects_path, method: :get, id: "searchForm" do %>
  <div class="input-group">  
    <%= text_field_tag :query_text, params[:query_text], 
      placeholder: "Search projects..." ,class: "form-control" %>
       <div class="input-group-btn">    
    </div>  
  </div>
  <% end %>  
</div>

<br>
<p class="float-right">
  <%= link_to "New Project", new_project_path, class: "btn btn-md btn-primary" %>
</p>

<% unless @projects.blank? %>
  <table class="table table-hover table-bordered table-striped">
    <thead>
      <tr>
        <th>Sl No.</th>
        <th>Name</th>
        <th>Tech Stack</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each_with_index do |project, index| %>
        <tr>
          <td><%= index + 1 %></td>  
          <td><%= project.name %></td>
          <td><%= project.tech_stack %></td>
          <td>
            <div class="btn-stack">
              <%= link_to "Show", project_path(project), 
                class: "btn btn-sm btn-success" %>
              <%= link_to "Edit", edit_project_path(project), 
                class: "btn btn-sm btn-primary" %>
              <%= link_to "Remove", project_path(project), method: :delete,
                data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
            </div>
          </td>
        </tr>
      <% end %> 
    </tbody>
  </table>
<% else %>
  <center><h3>No project found to be shown here!</h3></center>
<% end %>





<link href=" http://code.jquery.com/ui/1.9.1/themes/pepper-grinder/jquery-ui.css" rel="Stylesheet">
</link>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  
<script type="text/javascript">
  $("#query_text").autocomplete({
    minLength: 1,
    source: "<%= auto_suggest_projects_path %>",
    select: function(event, ui) {
      $("#query_text").val(ui.item.name);
      $("#searchForm").submit();
      return false;
    }
  }).data("ui-autocomplete")._renderItem = function(ul,item) {
    return $("<li class='list-group-item list-group-item-primary'></li>")
    .data("item.autocomplete", item)
    .append("<a>"+item.name+"</a>")
    .appendTo(ul);
  }
</script>

app/views/projects/new.html.erb
<div class="spacing">
  <link rel="stylesheet" href="application.scss">

  <h1 style="color:Tomato;">Create a Project</h1>
  <%= render "form" %>

</div>

app/views/projects/show.html.erb
<h3 style="color:Tomato;">Project Details</h3>
<div>
<table class="table table-hover table-bordered table-striped ">
<pre>
  <tr>
 <td><b>Name: </b><%= @project.name%></b></td></tr>
<tr>
<td><b>Description: </b><%= @project.description%></b></td></tr>
<tr>
<td><b>Tech stack: </b><%= @project.tech_stack %></b></td></tr>
<tr>
<td><b>Client details: </b><%= @project.clent_details %></b></pre></td></tr>
<tr>
        
        <td><b>Assigned Employee(s):
          <ul class="list-group">
            <% @project.employees.each do |emp| %>
              <li class="list-group-item list-group-item-info">
                <%= emp.emp_name %>
              </li></ul><%end%>
</table>
</div>
<br>
<div>
<%= link_to 'Remove', @project, method: :delete,
  class: "btn btn-sm btn-danger", data: { confirm: 'Are you sure?' } %>

<%= link_to 'Back', projects_path,class: "btn btn-sm btn-primary" %></div>